
services:
  dev-db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    ports:
      - 5432:5432
    networks:
      - nestjs-network

networks:
  nestjs-network:
    driver: bridge
