export const ENUM_DEFINITIONS = {  UserRole: {
    values: ['ADMIN', 'AUDITOR'] as const,
    description: 'Defines user access levels. ADMIN has full control; AUDITOR can only scan and report.',
  },
  AssetStatus: {
    values: ['GOOD', 'DAMAGED', 'REPAIR', 'BROKEN', 'TO_REPLACE'] as const,
    description:
      'Current physical condition of an asset. GOOD = working fine, DAMAGED = has issues but functional, REPAIR = currently being repaired, BROKEN = non-functional, TO_REPLACE = needs to be replaced.',
  },
  LocationType: {
    values: ['HOTEL', 'FLOOR', 'ZONE', 'SUBZONE'] as const,
    description:
      'Hierarchical level of a location. HOTEL is the root, FLOOR is a story, ZONE is an area within a floor (e.g., Lobby, Pool), SUBZONE is a specific spot within a zone (e.g., Room 101).',
  },
  AlertType: {
    values: ['DAMAGED', 'REPAIR', 'REPLACE', 'NOT_SCANNED'] as const,
    description:
      'Type of alert raised. DAMAGED = item found damaged during scan, REPAIR = needs repair, REPLACE = end of life must be replaced, NOT_SCANNED = item was not scanned during the last audit cycle.',
  },
  AlertStatus: {
    values: ['OPEN', 'RESOLVED'] as const,
    description: 'Workflow state of an alert. OPEN = pending action, RESOLVED = fixed or dismissed.',
  },
};

export interface SchemaField {
  name: string;
  type: string;
  description: string;
  isRelation?: boolean;
  isOptional?: boolean;
  isUnique?: boolean;
  isEnum?: boolean;
}

export interface SchemaRelationship {
  model: string;
  type: 'belongsTo' | 'hasMany' | 'hasOne';
  foreignKey: string;
  description: string;
  namedRelation?: string;
}

export interface SchemaTable {
  prismaModel: string;
  dbTable: string;
  description: string;
  synonyms: string[];
  fields: SchemaField[];
  relationships: SchemaRelationship[];
}

export const SCHEMA_MAP: SchemaTable[] = [
  {
    prismaModel: 'user',
    dbTable: 'users',
    description:
      'Represents a staff member or administrator who uses the system. Users can be ADMIN (full access) or AUDITOR (scan and report only). Each user has an email login and can perform scans, generate reports, log asset changes, and move assets.',
    synonyms: [
      'staff', 'employee', 'worker', 'team member', 'auditor',
      'admin', 'personnel', 'agent', 'operator', 'utilisateur',
    ],
    fields: [
      { name: 'id', type: 'String (UUID)', description: 'Unique identifier for the user.' },
      { name: 'name', type: 'String', description: 'Full name of the user.' },
      { name: 'email', type: 'String', description: 'Unique email address used for login.', isUnique: true },
      { name: 'password', type: 'String', description: 'Hashed password. Never expose this in queries.' },
      { name: 'role', type: 'UserRole', description: 'Access level: ADMIN or AUDITOR.', isEnum: true },
      { name: 'created_at', type: 'DateTime', description: 'Timestamp when the user account was created.' },
      { name: 'hashedRefreshToken', type: 'String?', description: 'Hashed JWT refresh token for authentication. Internal use only.', isOptional: true },
    ],
    relationships: [
      { model: 'Scan', type: 'hasMany', foreignKey: 'user_id', description: 'All scans performed by this user.' },
      { model: 'Report', type: 'hasMany', foreignKey: 'generated_by', description: 'All reports generated by this user.' },
      { model: 'AssetHistory', type: 'hasMany', foreignKey: 'user_id', description: 'All asset change logs attributed to this user.' },
      { model: 'AssetMovement', type: 'hasMany', foreignKey: 'user_id', description: 'All asset movements performed by this user.' },
    ],
  },
  {
    prismaModel: 'asset',
    dbTable: 'assets',
    description:
      'Represents a physical item, product, or resource in the hotel. Every asset has a unique RFID tag, belongs to a category, was purchased from a supplier, and is assigned to a specific location. The status field tracks its current physical condition.',
    synonyms: [
      'product', 'item', 'equipment', 'resource', 'inventory',
      'furniture', 'device', 'unit', 'material', 'object',
      'actif', 'produit', 'matériel', 'bien',
    ],
    fields: [
      { name: 'id', type: 'String (UUID)', description: 'Unique identifier for the asset.' },
      { name: 'tag_id', type: 'String?', description: 'Unique RFID or barcode tag. Use this for scanning lookups.', isUnique: true, isOptional: true },
      { name: 'name', type: 'String', description: 'Human-readable name of the asset (e.g., "Samsung 55\" TV").' },
      { name: 'category_id', type: 'String (UUID)', description: 'Foreign key to the Category table.' },
      { name: 'brand', type: 'String', description: 'Manufacturer brand (e.g., Samsung, Bosch).' },
      { name: 'model', type: 'String', description: 'Model name or number of the product.' },
      { name: 'supplier_id', type: 'String (UUID)', description: 'Foreign key to the Supplier who sold this item.' },
      { name: 'purchase_date', type: 'DateTime', description: 'Date the asset was purchased.' },
      { name: 'price', type: 'Decimal(10,2)', description: 'Purchase price in EUR. Use for financial aggregations like SUM, AVG.' },
      { name: 'warranty_end', type: 'DateTime?', description: 'Date the warranty expires. NULL means no warranty.', isOptional: true },
      { name: 'location_id', type: 'String (UUID)', description: 'Foreign key to the Location where the asset is currently placed.' },
      { name: 'status', type: 'AssetStatus', description: 'Current physical condition: GOOD, DAMAGED, REPAIR, BROKEN, or TO_REPLACE.', isEnum: true },
      { name: 'created_at', type: 'DateTime', description: 'Timestamp when the asset was registered in the system.' },
      { name: 'image_url', type: 'String?', description: 'URL of the asset photo.', isOptional: true },
    ],
    relationships: [
      { model: 'Category', type: 'belongsTo', foreignKey: 'category_id', description: 'The category this asset belongs to (e.g., Electronics, Furniture).' },
      { model: 'Supplier', type: 'belongsTo', foreignKey: 'supplier_id', description: 'The supplier/vendor who sold this asset.' },
      { model: 'Location', type: 'belongsTo', foreignKey: 'location_id', description: 'The current physical location of this asset within the hotel.' },
      { model: 'Scan', type: 'hasMany', foreignKey: 'asset_id', description: 'All audit scans performed on this asset.' },
      { model: 'Alert', type: 'hasMany', foreignKey: 'asset_id', description: 'All alerts raised for this asset (damage, repair, etc.).' },
      { model: 'AssetHistory', type: 'hasMany', foreignKey: 'asset_id', description: 'Complete changelog of all actions performed on this asset.' },
      { model: 'AssetMovement', type: 'hasMany', foreignKey: 'asset_id', description: 'All physical movements/transfers of this asset between locations.' },
    ],
  },
  {
    prismaModel: 'location',
    dbTable: 'locations',
    description:
      'Represents a physical place in the hotel organized in a hierarchy: HOTEL → FLOOR → ZONE → SUBZONE. Each location can have a parent (forming a tree structure). Assets, scans, alerts, and movements are all linked to locations. Use the "children" relation to find all sub-locations under a given location.',
    synonyms: [
      'place', 'room', 'area', 'floor', 'zone', 'site', 'spot',
      'destination', 'level', 'wing', 'section', 'emplacement',
      'étage', 'lieu',
    ],
    fields: [
      { name: 'id', type: 'String (UUID)', description: 'Unique identifier for the location.' },
      { name: 'name', type: 'String', description: 'Human-readable name (e.g., "Floor 1", "VIP Lounge", "Room 301").' },
      { name: 'parent_id', type: 'String? (UUID)', description: 'Foreign key to the parent location. NULL means this is the root (Hotel level).', isOptional: true },
      { name: 'type', type: 'LocationType', description: 'Hierarchy level: HOTEL, FLOOR, ZONE, or SUBZONE.', isEnum: true },
    ],
    relationships: [
      { model: 'Location', type: 'belongsTo', foreignKey: 'parent_id', description: 'The parent location in the hierarchy (e.g., a Zone belongs to a Floor).', namedRelation: 'LocationHierarchy' },
      { model: 'Location', type: 'hasMany', foreignKey: 'parent_id', description: 'All child locations under this location (e.g., all Zones on a Floor).', namedRelation: 'LocationHierarchy' },
      { model: 'Asset', type: 'hasMany', foreignKey: 'location_id', description: 'All assets currently placed in this location.' },
      { model: 'Scan', type: 'hasMany', foreignKey: 'location_id', description: 'All scans that took place at this location.' },
      { model: 'Alert', type: 'hasMany', foreignKey: 'location_id', description: 'All alerts linked to this location.' },
      { model: 'AssetMovement', type: 'hasMany', foreignKey: 'to_location_id', description: 'All movements where assets arrived at this location.', namedRelation: 'ToLocation' },
      { model: 'AssetMovement', type: 'hasMany', foreignKey: 'from_location_id', description: 'All movements where assets departed from this location.', namedRelation: 'FromLocation' },
    ],
  },
  {
    prismaModel: 'category',
    dbTable: 'categories',
    description:
      'A classification group for assets (e.g., "Electronics", "Furniture", "Kitchen Equipment", "Bathroom Accessories"). Each asset belongs to exactly one category. Use this to group or filter assets by type.',
    synonyms: [
      'type', 'group', 'class', 'department', 'kind',
      'classification', 'catégorie',
    ],
    fields: [
      { name: 'id', type: 'String (UUID)', description: 'Unique identifier for the category.' },
      { name: 'name', type: 'String', description: 'Unique category name (e.g., "Electronics", "Linens").', isUnique: true },
    ],
    relationships: [
      { model: 'Asset', type: 'hasMany', foreignKey: 'category_id', description: 'All assets that belong to this category.' },
    ],
  },
  {
    prismaModel: 'supplier',
    dbTable: 'suppliers',
    description:
      'A vendor or provider that supplies products to the hotel. Each asset is linked to the supplier it was purchased from. Useful for procurement tracking, warranty claims, and reordering.',
    synonyms: [
      'vendor', 'provider', 'seller', 'merchant', 'manufacturer',
      'source', 'distributor', 'fournisseur',
    ],
    fields: [
      { name: 'id', type: 'String (UUID)', description: 'Unique identifier for the supplier.' },
      { name: 'name', type: 'String', description: 'Company name of the supplier.' },
      { name: 'contact_email', type: 'String?', description: 'Email address for contacting the supplier.', isOptional: true },
      { name: 'phone', type: 'String?', description: 'Phone number of the supplier.', isOptional: true },
    ],
    relationships: [
      { model: 'Asset', type: 'hasMany', foreignKey: 'supplier_id', description: 'All assets supplied by this vendor.' },
    ],
  },
  {
    prismaModel: 'scan',
    dbTable: 'scans',
    description:
      'Records a single audit event where a user scanned an asset at a specific location. Each scan captures WHO scanned, WHAT was scanned, WHERE, WHEN, and the observed STATUS at that moment. Scans are the core of the audit workflow.',
    synonyms: [
      'check', 'audit', 'inspection', 'verification', 'review',
      'reading', 'RFID scan', 'contrôle', 'vérification',
    ],
    fields: [
      { name: 'id', type: 'String (UUID)', description: 'Unique identifier for the scan record.' },
      { name: 'asset_id', type: 'String (UUID)', description: 'Foreign key to the Asset that was scanned.' },
      { name: 'user_id', type: 'String (UUID)', description: 'Foreign key to the User who performed the scan.' },
      { name: 'location_id', type: 'String (UUID)', description: 'Foreign key to the Location where the scan happened.' },
      { name: 'status', type: 'AssetStatus', description: 'The observed condition of the asset at scan time: GOOD, DAMAGED, REPAIR, BROKEN, or TO_REPLACE.', isEnum: true },
      { name: 'scanned_at', type: 'DateTime', description: 'Timestamp when the scan was performed.' },
    ],
    relationships: [
      { model: 'Asset', type: 'belongsTo', foreignKey: 'asset_id', description: 'The asset that was scanned.' },
      { model: 'User', type: 'belongsTo', foreignKey: 'user_id', description: 'The staff member who performed this scan.' },
      { model: 'Location', type: 'belongsTo', foreignKey: 'location_id', description: 'The location where this scan took place.' },
      { model: 'AssetMovement', type: 'hasMany', foreignKey: 'scan_id', description: 'Any asset movements triggered by this scan.' },
    ],
  },
  {
    prismaModel: 'alert',
    dbTable: 'alerts',
    description:
      'Represents a problem, issue, or warning that requires attention. Alerts can be linked to a specific asset (e.g., "TV is broken"), a location (e.g., "water leak on Floor 2"), or both. Alerts have a workflow status: OPEN (needs action) or RESOLVED (fixed).',
    synonyms: [
      'problem', 'issue', 'damage', 'warning', 'notification',
      'incident', 'defect', 'fault', 'alerte', 'signalement',
    ],
    fields: [
      { name: 'id', type: 'String (UUID)', description: 'Unique identifier for the alert.' },
      { name: 'asset_id', type: 'String? (UUID)', description: 'Foreign key to the related Asset. NULL if the alert is location-only.', isOptional: true },
      { name: 'location_id', type: 'String? (UUID)', description: 'Foreign key to the related Location. NULL if the alert is asset-only.', isOptional: true },
      { name: 'type', type: 'AlertType', description: 'Nature of the alert: DAMAGED, REPAIR, REPLACE, or NOT_SCANNED.', isEnum: true },
      { name: 'status', type: 'AlertStatus', description: 'Workflow state: OPEN (pending) or RESOLVED (fixed).', isEnum: true },
      { name: 'created_at', type: 'DateTime', description: 'Timestamp when the alert was raised.' },
      { name: 'comment', type: 'String?', description: 'Free-text description of the issue observed by the auditor.', isOptional: true },
      { name: 'photo_url', type: 'String?', description: 'URL of a photo documenting the damage. DB column is "image_url".', isOptional: true },
    ],
    relationships: [
      { model: 'Asset', type: 'belongsTo', foreignKey: 'asset_id', description: 'The asset this alert is about (if applicable).' },
      { model: 'Location', type: 'belongsTo', foreignKey: 'location_id', description: 'The location this alert is about (if applicable).' },
    ],
  },
  {
    prismaModel: 'report',
    dbTable: 'reports',
    description:
      'Stores metadata about generated reports. Each report is created by a user (generated_by) and has a type (e.g., "inventory_summary", "maintenance_report"). The filters field stores the JSON criteria used to generate the report.',
    synonyms: [
      'summary', 'stats', 'data export', 'analytics', 'results',
      'document', 'output', 'rapport', 'bilan',
    ],
    fields: [
      { name: 'id', type: 'String (UUID)', description: 'Unique identifier for the report.' },
      { name: 'generated_by', type: 'String (UUID)', description: 'Foreign key to the User who generated this report.' },
      { name: 'report_type', type: 'String', description: 'Type of report (e.g., "inventory_summary", "damage_report").' },
      { name: 'filters', type: 'Json?', description: 'JSON object storing the filter criteria used (e.g., { status: "BROKEN", floor: "Floor 1" }).', isOptional: true },
      { name: 'created_at', type: 'DateTime', description: 'Timestamp when the report was generated.' },
    ],
    relationships: [
      { model: 'User', type: 'belongsTo', foreignKey: 'generated_by', description: 'The user who generated this report.' },
    ],
  },
  {
    prismaModel: 'assetHistory',
    dbTable: 'asset_history',
    description:
      'An immutable audit log of all actions performed on an asset. Every create, update, status change, or deletion is recorded here with WHO did it and WHEN. Use this for accountability, compliance, and tracking the full lifecycle of an asset.',
    synonyms: [
      'log', 'history', 'changes', 'tracking', 'audit trail',
      'record', 'changelog', 'timeline', 'historique',
    ],
    fields: [
      { name: 'id', type: 'String (UUID)', description: 'Unique identifier for the history entry.' },
      { name: 'asset_id', type: 'String (UUID)', description: 'Foreign key to the Asset this log entry is about.' },
      { name: 'action', type: 'String', description: 'Description of the action performed (e.g., "STATUS_CHANGED", "CREATED", "MOVED").' },
      { name: 'user_id', type: 'String (UUID)', description: 'Foreign key to the User who performed this action.' },
      { name: 'timestamp', type: 'DateTime', description: 'When this action was performed.' },
    ],
    relationships: [
      { model: 'Asset', type: 'belongsTo', foreignKey: 'asset_id', description: 'The asset this history entry belongs to.' },
      { model: 'User', type: 'belongsTo', foreignKey: 'user_id', description: 'The user who performed the action.' },
    ],
  },
  {
    prismaModel: 'assetMovement',
    dbTable: 'asset_movements',
    description:
      'Records a physical transfer of an asset from one location to another. Tracks the source location (from_location), destination (to_location), who moved it (user), and optionally which scan triggered the movement. from_location is NULL for the first placement of a new asset.',
    synonyms: [
      'transfer', 'move', 'relocation', 'migration', 'shift',
      'transport', 'displacement', 'déplacement', 'mouvement',
    ],
    fields: [
      { name: 'id', type: 'String (UUID)', description: 'Unique identifier for the movement record.' },
      { name: 'asset_id', type: 'String (UUID)', description: 'Foreign key to the Asset that was moved.' },
      { name: 'from_location_id', type: 'String? (UUID)', description: 'Foreign key to the source Location. NULL if the asset is being placed for the first time.', isOptional: true },
      { name: 'to_location_id', type: 'String (UUID)', description: 'Foreign key to the destination Location.' },
      { name: 'user_id', type: 'String (UUID)', description: 'Foreign key to the User who performed the move.' },
      { name: 'scan_id', type: 'String? (UUID)', description: 'Foreign key to the Scan that triggered this movement (if any).', isOptional: true },
      { name: 'moved_at', type: 'DateTime', description: 'Timestamp when the asset was moved.' },
    ],
    relationships: [
      { model: 'Asset', type: 'belongsTo', foreignKey: 'asset_id', description: 'The asset that was physically moved.' },
      { model: 'Location', type: 'belongsTo', foreignKey: 'from_location_id', description: 'Where the asset came FROM.', namedRelation: 'FromLocation' },
      { model: 'Location', type: 'belongsTo', foreignKey: 'to_location_id', description: 'Where the asset went TO (current destination).', namedRelation: 'ToLocation' },
      { model: 'User', type: 'belongsTo', foreignKey: 'user_id', description: 'The staff member who performed the transfer.' },
      { model: 'Scan', type: 'belongsTo', foreignKey: 'scan_id', description: 'The scan that triggered this movement (if applicable).' },
    ],
  },
];

/** Prisma client model names in this project, in a stable order. */
export const PRISMA_MODEL_IDENTIFIERS: readonly string[] = SCHEMA_MAP.map((t) => t.prismaModel);

const canonicalModelByLower = new Map(
    SCHEMA_MAP.map((t) => [t.prismaModel.toLowerCase(), t.prismaModel]),
);

/** Full text passed to the LLM for phase-1 table resolution. */
export function getTableResolutionContext(): string {
    const ids = PRISMA_MODEL_IDENTIFIERS.join(', ');
    return [
        `Allowed Prisma model identifiers (return only these exact strings in "tables"): ${ids}`,
        '',
        '## Model overview',
        getSchemaOverview(),
        '',
        '## Enums',
        getEnumDefinitions(),
    ].join('\n');
}

/** Maps any casing to the canonical prismaModel, or undefined if unknown. */
export function normalizePrismaModelName(name: string): string | undefined {
    return canonicalModelByLower.get(name.trim().toLowerCase());
}

export function getSchemaOverview(): string {
  return SCHEMA_MAP.map(
    (t) =>
      `• ${t.prismaModel} (DB: "${t.dbTable}"): ${t.description}\n  Synonyms: ${t.synonyms.join(', ')}`,
  ).join('\n\n');
}

export function getTableDefinitions(tableNames: string[]): string {
  const lower = tableNames.map((n) => n.toLowerCase());
  const matched = SCHEMA_MAP.filter(
    (t) =>
      lower.includes(t.prismaModel.toLowerCase()) ||
      lower.includes(t.dbTable.toLowerCase()),
  );

  return matched
    .map((t) => {
      const fields = t.fields
        .map((f) => `    - ${f.name} (${f.type}): ${f.description}`)
        .join('\n');
      const rels = t.relationships
        .map(
          (r) =>
            `    - ${r.type === 'belongsTo' ? '→' : '←'} ${r.model} via "${r.foreignKey}": ${r.description}`,
        )
        .join('\n');
      return `Model: ${t.prismaModel} (table: "${t.dbTable}")\n  Description: ${t.description}\n  Fields:\n${fields}\n  Relationships:\n${rels}`;
    })
    .join('\n\n---\n\n');
}

export function getEnumDefinitions(): string {
  return Object.entries(ENUM_DEFINITIONS)
    .map(
      ([name, def]) =>
        `• ${name}: [${def.values.join(', ')}] — ${def.description}`,
    )
    .join('\n');
}
